# Laptop Price Prediction using Machine Learning

This notebook trains a machine learning model to predict laptop prices based on specifications such as RAM, CPU, GPU, storage, and screen size.

Workflow:
1. Load dataset
2. Data preprocessing
3. Feature encoding
4. Model training
5. Model evaluation
6. Export model

# Import Libraries

In [1]:
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Load Dataset

In [2]:
df = pd.read_csv("dataset.csv")
df.head()

,LaptopName,Company,RAM,SSD,HDD,CPU,GPU,ScreenSize,Weight,OS,Price
0,Acer Swift 3,Acer,16,256,1000,Ryzen5,Intel,14.0,2.65,Windows,69893
1,Lenovo Legion 5,Lenovo,32,512,500,i3,AMD,15.6,1.59,Windows,82594
2,Acer Aspire Lite,Acer,8,256,500,Ryzen5,AMD,15.6,2.64,Windows,62393
3,Lenovo ThinkPad X1,Lenovo,8,512,500,i5,AppleGPU,17.0,1.20,Windows,53363
4,HP Omen 16,HP,32,1024,1000,i3,AppleGPU,16.0,1.55,Windows,82498

# Dataset Information

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LaptopName  400 non-null    object
 1   Company     400 non-null    object
 2   RAM         400 non-null    int64
 3   SSD         400 non-null    int64
 4   HDD         400 non-null    int64
 5   CPU         400 non-null    object
 6   GPU         400 non-null    object
 7   ScreenSize  400 non-null    float64
 8   Weight      400 non-null    float64
 9   OS          400 non-null    object
 10  Price       400 non-null    int64
dtypes: float64(2), int64(4), object(5)
memory usage: 34.5+ KB

In [4]:
df.describe()

,RAM,SSD,HDD,ScreenSize,Weight,Price
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,18.240000,575.360000,492.500000,15.153750,1.919550,101176.350000
std,10.057599,320.784362,415.783525,1.338737,0.455307,37339.374844
min,8.000000,256.000000,0.000000,13.300000,1.100000,38930.000000
25%,8.000000,256.000000,0.000000,14.000000,1.520000,71722.000000
50%,16.000000,512.000000,500.000000,15.600000,1.920000,93502.000000
75%,32.000000,1024.000000,1000.000000,16.000000,2.300000,125018.000000
max,32.000000,1024.000000,1000.000000,17.000000,2.690000,206346.000000

# Check Missing values

In [5]:
df.isnull().sum()

LaptopName    0
Company       0
RAM           0
SSD           0
HDD           0
CPU           0
GPU           0
ScreenSize    0
Weight        0
OS            0
Price         0
dtype: int64

# Encoding Categorical Columns

In [6]:
encoders = {}

for col in ["Company","CPU","GPU","OS"]:
    
    le = LabelEncoder()
    
    df[col] = le.fit_transform(df[col])
    
    encoders[col] = le

# Feature Selection

In [7]:
X = df.drop(["LaptopName","Price"],axis=1)

y = df["Price"]

# Scale Features

In [8]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# Train-Test Split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(
    
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# Model Training

In [10]:
model = RandomForestRegressor(
    
    n_estimators=800,
    max_depth=18,
    random_state=42
)

model.fit(X_train,y_train)

RandomForestRegressor(max_depth=18, n_estimators=800, random_state=42)

# Model Evaluation

In [11]:
pred = model.predict(X_test)

print("Model R2 Score:",r2_score(y_test,pred))

Model R2 Score: 0.9785600777058776

# Save Model

In [12]:
pickle.dump(model,open("model.pkl","wb"))
pickle.dump(encoders,open("encoders.pkl","wb"))
pickle.dump(scaler,open("scaler.pkl","wb"))